services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:123456@db:5432/Todosapp"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: Todosapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

volumes:
  postgres_data: